workflow:
  name: Generate ASCII Artwork

build_job:
  before_script:
    - gem install cowsay
    - sleep 30s
  script:
    - >
        cowsay -f dragon "Run for cover,
        I am a DRAGON....RAWR" >> dragon.txt

test_job:
  script:
    - |
       sleep 10s
       grep -i "dragon" dragon.txt

deploy_job:
  script:
    - cat dragon.txt
    - echo "deploying........"
#Pipeline fails because of it consists of multiple dependent job, but it is executed as parallel jobs