workflow:
  name: Generate ASCII Artwork

ascii_job:
  before_script:
    - gem install cowsay
    - chmod +x ascii-script.sh  #without permissions script cannot execute and pipeline will fail
  script:
    - ./ascii-script.sh #provide script name along with path
  after_script:
    - echo "Executed at the end, can be used for cleaning/removing content"